#ifndef INCLUDE_NBT_VERSION_H_
#define INCLUDE_NBT_VERSION_H_

#define NBT_VERSION_MAJOR 1
#define NBT_VERSION_MINOR 0
#define NBT_VERSION_PATCH 1
#define NBT_VERSION_STRING "1.0.1"

#endif  // INCLUDE_NBT_VERSION_H_
